### ISSUE TITLE
Error when debug app

### ISSUE THREAD

**Issue by ShillTool** [GarudaID/android-webview-admod#1]
![image](https://user-images.githubusercontent.com/102027117/230700046-49185368-9c65-4e1f-ab2d-47bb4d1aeb45.png)

please fix

**Comment by GarudaID** [comment]
> ![image](https://user-images.githubusercontent.com/102027117/230700046-49185368-9c65-4e1f-ab2d-47bb4d1aeb45.png)
> 
> please fix

thanks for send error ... please follow this step 

go to MainActivity.java

`private NdefRecord createRecord(String text) throws UnsupportedEncodingException {
}
    private NdefRecord createRecord(String text)
            throws UnsupportedEncodingException {
        if (text.startsWith("VCARD")) {
            String nameVcard = "BEGIN:" +
                    text.replace('_', '\n').replace("%20", " ")
                    + '\n' + "END:VCARD";
            byte[] uriField = nameVcard.getBytes(StandardCharsets.US_ASCII);
            byte[] payload = new byte[uriField.length + 1];              //add 1 for the URI Prefix
            //payload[0] = 0x01;                                      //prefixes http://www. to the URI
            System.arraycopy(uriField, 0, payload, 1, uriField.length);  //appends URI to payload`

**Comment by ShillTool** [comment]
> > ![image](https://user-images.githubusercontent.com/102027117/230700046-49185368-9c65-4e1f-ab2d-47bb4d1aeb45.png)
> > please fix
> 
> thanks for send error ... please follow this step
> 
> go to MainActivity.java jump to line 3142 then copy this code
> 
> ```
> private NdefRecord createRecord(String text) throws UnsupportedEncodingException {
> }
>     private NdefRecord createRecord(String text)
>             throws UnsupportedEncodingException {
>         if (text.startsWith("VCARD")) {
> 
>             String nameVcard = "BEGIN:" +
>                     text.replace('_', '\n').replace("%20", " ")
>                     + '\n' + "END:VCARD";
>             byte[] uriField = nameVcard.getBytes(StandardCharsets.US_ASCII);
>             byte[] payload = new byte[uriField.length + 1];              //add 1 for the URI Prefix
>             //payload[0] = 0x01;                                      //prefixes http://www. to the URI
>             System.arraycopy(uriField, 0, payload, 1, uriField.length);  //appends URI to payload
> ```

ok let me check

**Comment by ShillTool** [comment]
> > ![image](https://user-images.githubusercontent.com/102027117/230700046-49185368-9c65-4e1f-ab2d-47bb4d1aeb45.png)
> > please fix
> 
> thanks for send error ... please follow this step
> 
> go to MainActivity.java jump to line 3142 then copy this code
> 
> ```
> private NdefRecord createRecord(String text) throws UnsupportedEncodingException {
> }
>     private NdefRecord createRecord(String text)
>             throws UnsupportedEncodingException {
>         if (text.startsWith("VCARD")) {
> 
>             String nameVcard = "BEGIN:" +
>                     text.replace('_', '\n').replace("%20", " ")
>                     + '\n' + "END:VCARD";
>             byte[] uriField = nameVcard.getBytes(StandardCharsets.US_ASCII);
>             byte[] payload = new byte[uriField.length + 1];              //add 1 for the URI Prefix
>             //payload[0] = 0x01;                                      //prefixes http://www. to the URI
>             System.arraycopy(uriField, 0, payload, 1, uriField.length);  //appends URI to payload
> ```

not yet fix please check

**Comment by GarudaID** [comment]
> > > ![image](https://user-images.githubusercontent.com/102027117/230700046-49185368-9c65-4e1f-ab2d-47bb4d1aeb45.png)
> > > please fix
> > 
> > 
> > thanks for send error ... please follow this step
> > go to MainActivity.java jump to line 3142 then copy this code
> > ```
> > private NdefRecord createRecord(String text) throws UnsupportedEncodingException {
> > }
> >     private NdefRecord createRecord(String text)
> >             throws UnsupportedEncodingException {
> >         if (text.startsWith("VCARD")) {
> > 
> >             String nameVcard = "BEGIN:" +
> >                     text.replace('_', '\n').replace("%20", " ")
> >                     + '\n' + "END:VCARD";
> >             byte[] uriField = nameVcard.getBytes(StandardCharsets.US_ASCII);
> >             byte[] payload = new byte[uriField.length + 1];              //add 1 for the URI Prefix
> >             //payload[0] = 0x01;                                      //prefixes http://www. to the URI
> >             System.arraycopy(uriField, 0, payload, 1, uriField.length);  //appends URI to payload
> > ```
> 
> not yet fix please check. Seem bug with line 316

Okey I will fix this code tomorrow

**Comment by ShillTool** [comment]
> > > > ![image](https://user-images.githubusercontent.com/102027117/230700046-49185368-9c65-4e1f-ab2d-47bb4d1aeb45.png)
> > > > please fix
> > > 
> > > 
> > > thanks for send error ... please follow this step
> > > go to MainActivity.java jump to line 3142 then copy this code
> > > ```
> > > private NdefRecord createRecord(String text) throws UnsupportedEncodingException {
> > > }
> > >     private NdefRecord createRecord(String text)
> > >             throws UnsupportedEncodingException {
> > >         if (text.startsWith("VCARD")) {
> > > 
> > >             String nameVcard = "BEGIN:" +
> > >                     text.replace('_', '\n').replace("%20", " ")
> > >                     + '\n' + "END:VCARD";
> > >             byte[] uriField = nameVcard.getBytes(StandardCharsets.US_ASCII);
> > >             byte[] payload = new byte[uriField.length + 1];              //add 1 for the URI Prefix
> > >             //payload[0] = 0x01;                                      //prefixes http://www. to the URI
> > >             System.arraycopy(uriField, 0, payload, 1, uriField.length);  //appends URI to payload
> > > ```
> > 
> > 
> > not yet fix please check. Seem bug with line 316
> 
> Okey I will fix this code tomorrow

Ok thanks please fix tomorow. Can you share discord link group ? I want to join

**Comment by ShillTool** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/102027117/230700046-49185368-9c65-4e1f-ab2d-47bb4d1aeb45.png)
> > > > > > please fix
> > > > > 
> > > > > 
> > > > > thanks for send error ... please follow this step
> > > > > go to MainActivity.java jump to line 3142 then copy this code
> > > > > ```
> > > > > private NdefRecord createRecord(String text) throws UnsupportedEncodingException {
> > > > > }
> > > > >     private NdefRecord createRecord(String text)
> > > > >             throws UnsupportedEncodingException {
> > > > >         if (text.startsWith("VCARD")) {
> > > > > 
> > > > >             String nameVcard = "BEGIN:" +
> > > > >                     text.replace('_', '\n').replace("%20", " ")
> > > > >                     + '\n' + "END:VCARD";
> > > > >             byte[] uriField = nameVcard.getBytes(StandardCharsets.US_ASCII);
> > > > >             byte[] payload = new byte[uriField.length + 1];              //add 1 for the URI Prefix
> > > > >             //payload[0] = 0x01;                                      //prefixes http://www. to the URI
> > > > >             System.arraycopy(uriField, 0, payload, 1, uriField.length);  //appends URI to payload
> > > > > ```
> > > > 
> > > > 
> > > > not yet fix please check. Seem bug with line 316
> > > 
> > > 
> > > Okey I will fix this code tomorrow
> > 
> > 
> > Ok thanks please fix tomorow. Can you share discord link group ? I want to join
> 
> Follow + star my github first i will fix right now

Ok i will flow. Please notice me if fix done

**Comment by GarudaID** [comment]
> > > > > > > ![image](https://user-images.githubusercontent.com/102027117/230700046-49185368-9c65-4e1f-ab2d-47bb4d1aeb45.png)
> > > > > > > please fix
> > > > > > 
> > > > > > 
> > > > > > thanks for send error ... please follow this step
> > > > > > go to MainActivity.java jump to line 3142 then copy this code
> > > > > > ```
> > > > > > private NdefRecord createRecord(String text) throws UnsupportedEncodingException {
> > > > > > }
> > > > > >     private NdefRecord createRecord(String text)
> > > > > >             throws UnsupportedEncodingException {
> > > > > >         if (text.startsWith("VCARD")) {
> > > > > > 
> > > > > >             String nameVcard = "BEGIN:" +
> > > > > >                     text.replace('_', '\n').replace("%20", " ")
> > > > > >                     + '\n' + "END:VCARD";
> > > > > >             byte[] uriField = nameVcard.getBytes(StandardCharsets.US_ASCII);
> > > > > >             byte[] payload = new byte[uriField.length + 1];              //add 1 for the URI Prefix
> > > > > >             //payload[0] = 0x01;                                      //prefixes http://www. to the URI
> > > > > >             System.arraycopy(uriField, 0, payload, 1, uriField.length);  //appends URI to payload
> > > > > > ```
> > > > > 
> > > > > 
> > > > > not yet fix please check. Seem bug with line 316
> > > > 
> > > > 
> > > > Okey I will fix this code tomorrow
> > > 
> > > 
> > > Ok thanks please fix tomorow. Can you share discord link group ? I want to join
> > 
> > 
> > Follow + star my github first i will fix right now
> 
> Ok i will flow. Please notice me if fix done

done, please check again

**Comment by ShillTool** [comment]
> > > > > > > > ![image](https://user-images.githubusercontent.com/102027117/230700046-49185368-9c65-4e1f-ab2d-47bb4d1aeb45.png)
> > > > > > > > please fix
> > > > > > > 
> > > > > > > 
> > > > > > > thanks for send error ... please follow this step
> > > > > > > go to MainActivity.java jump to line 3142 then copy this code
> > > > > > > ```
> > > > > > > private NdefRecord createRecord(String text) throws UnsupportedEncodingException {
> > > > > > > }
> > > > > > >     private NdefRecord createRecord(String text)
> > > > > > >             throws UnsupportedEncodingException {
> > > > > > >         if (text.startsWith("VCARD")) {
> > > > > > > 
> > > > > > >             String nameVcard = "BEGIN:" +
> > > > > > >                     text.replace('_', '\n').replace("%20", " ")
> > > > > > >                     + '\n' + "END:VCARD";
> > > > > > >             byte[] uriField = nameVcard.getBytes(StandardCharsets.US_ASCII);
> > > > > > >             byte[] payload = new byte[uriField.length + 1];              //add 1 for the URI Prefix
> > > > > > >             //payload[0] = 0x01;                                      //prefixes http://www. to the URI
> > > > > > >             System.arraycopy(uriField, 0, payload, 1, uriField.length);  //appends URI to payload
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > not yet fix please check. Seem bug with line 316
> > > > > 
> > > > > 
> > > > > Okey I will fix this code tomorrow
> > > > 
> > > > 
> > > > Ok thanks please fix tomorow. Can you share discord link group ? I want to join
> > > 
> > > 
> > > Follow + star my github first i will fix right now
> > 
> > 
> > Ok i will flow. Please notice me if fix done
> 
> done, please check again

thanks let me check

**Comment by ShillTool** [comment]
> > > > > > > > ![image](https://user-images.githubusercontent.com/102027117/230700046-49185368-9c65-4e1f-ab2d-47bb4d1aeb45.png)
> > > > > > > > please fix
> > > > > > > 
> > > > > > > 
> > > > > > > thanks for send error ... please follow this step
> > > > > > > go to MainActivity.java jump to line 3142 then copy this code
> > > > > > > ```
> > > > > > > private NdefRecord createRecord(String text) throws UnsupportedEncodingException {
> > > > > > > }
> > > > > > >     private NdefRecord createRecord(String text)
> > > > > > >             throws UnsupportedEncodingException {
> > > > > > >         if (text.startsWith("VCARD")) {
> > > > > > > 
> > > > > > >             String nameVcard = "BEGIN:" +
> > > > > > >                     text.replace('_', '\n').replace("%20", " ")
> > > > > > >                     + '\n' + "END:VCARD";
> > > > > > >             byte[] uriField = nameVcard.getBytes(StandardCharsets.US_ASCII);
> > > > > > >             byte[] payload = new byte[uriField.length + 1];              //add 1 for the URI Prefix
> > > > > > >             //payload[0] = 0x01;                                      //prefixes http://www. to the URI
> > > > > > >             System.arraycopy(uriField, 0, payload, 1, uriField.length);  //appends URI to payload
> > > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > not yet fix please check. Seem bug with line 316
> > > > > 
> > > > > 
> > > > > Okey I will fix this code tomorrow
> > > > 
> > > > 
> > > > Ok thanks please fix tomorow. Can you share discord link group ? I want to join
> > > 
> > > 
> > > Follow + star my github first i will fix right now
> > 
> > 
> > Ok i will flow. Please notice me if fix done
> 
> done, please check again

New bug: 
![image](https://user-images.githubusercontent.com/102027117/231037472-e3d8e410-5365-4944-8e8b-c5e25c779b5f.png)
